name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
# On met à jour la base de données AVANT de démarrer
predev = "npx prisma generate && npx prisma db push --accept-data-loss"

# On démarre le vrai serveur de développement (Vite) qui reste allumé
dev = "npm run vite"