# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3898419da69de8dbe2c3e5a705204fa0"
name = "App MM - MF/MO "
application_url = "https://app-mm-mf-mo.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_draft_orders,read_draft_orders,write_locations,read_locations,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_orders,write_orders,read_products,write_products,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://app-mm-mf-mo.onrender.com/auth/callback",
  "https://app-mm-mf-mo.onrender.com/auth/shopify/callback",
  "https://app-mm-mf-mo.onrender.com/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
