# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfaf53f397e6bf08186cb2a3ade9f065"
name = "Basilic App - Gestion"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,read_online_store_navigation"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[navigation]
[[navigation.left]]
label = "Champs Méta (MF)"
link = "/app/mf"

[[navigation.left]]
label = "Objets Méta (MO)"
link = "/app/mo"

[[navigation.left]]
label = "Templates"
link = "/app/templates"

[[navigation.left]]
label = "Menus"
link = "/app/menu"

[[navigation.left]]
label = "Médias"
link = "/app/media"
